title: Kris Lamoureux
url: "https://www.krislamo.org"

exclude:
  - Makefile

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"
locale: "en-US"
atom_feed:
  hide: true

footer:
  links: []

author:
  name: "Kris Lamoureux"
  avatar: "https://2.gravatar.com/avatar/a33713ab741271d63c888e\
           5df8112f227571e4dd5d31162b0920f175e81f78a6?size=256"
  bio: "Linux Systems Enthusiast"
  links:
    - label: "Gitea"
      icon: "fab fa-fw fa-git-alt"
      url: "https://git.krislamo.org/kris"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/krislamo"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/krislamo"
